name: 3.0 Linux

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100-preview8-013656'
    - name: Test 
      run: dotnet test DataStructure
